### ISSUE TITLE
Spurious page break

### ISSUE THREAD

**Issue by robogeek** [AlexDawsonUK/Printed#1]
I found this style sheet - and it looks pretty nice when installed.

I'm trying to have a situation with a cover page, then a table of contents, before the main content.  There should be a page break between the cover and the ToC, then another page break between the ToC and the main content.

But, there is a spurious page break between the H1 in the ToC section and the UL containing the ToC.

I narrowed it down to this declaration:

```css
	a, blockquote, canvas, details, dl, figure, img, ol, picture, svg, table /* , ul */ {
		break-inside: avoid;
		page-break-inside: avoid; }
```

Commenting out `ul` in this eliminated the spurious page break.  My theory is that the browser with the `page-break-inside` declaration here tries to fit the UL onto one page but it's a large enough UL that it spreads to a second page.

The HTML is structured like:

```html
<article class="col-md-12">
<div id="title-page" class="cover">
<!-- HTML for cover -->
</div>
<section id="contents" class="page_break" tabindex="-1">
<h1 class="page_break" tabindex="-1">CONTENTS</h1>
<div class="table-of-contents"><ul> ... </ul></div>
</section>

<!-- the rest of the content is a number of section tags -->
```

The `page_break` class is no longer defined, and `table-of-contents` is also not defined.  The `cover` class on `#title-page` is defined in your CSS as having a page break after.

This is defined:

```css
section#contents {
    page-break-after:  always;
    page-break-before: always;
    page-break-inside: avoid !important;
}
```

This should cause the page break after the CONTENTS section, and note that it targets the `<section>` and not the content inside the section.
